# .readthedocs.yml

# Build documentation in the docs/ directory with Sphinx
build:
  image: latest
  
# Build documentation in the docs/ directory with Sphinx
build:
  image: latest

# Define the version of documentation to be built
docs_version: latest