# Table of contents

* [언어](README.md)
* [Meeting Notes](en/README.md)
  * [Table of contents](en/SUMMARY.md)
  * [daily-syncs](en/daily-syncs/README.md)
    * [Design Standups](en/daily-syncs/design-standups/README.md)
      * [September 2021](en/daily-syncs/design-standups/september-2021/README.md)
        * [Week 1 (6 - 10 Sept)](en/daily-syncs/design-standups/september-2021/week-1-6-10-sept.md)
  * [other-regulars](en/other-regulars/README.md)
    * [Company Weeklies](en/other-regulars/company-weeklies/README.md)
      * [September 14th 2021](en/other-regulars/company-weeklies/september-14th-2021.md)
  * [weekly-syncs](en/weekly-syncs/README.md)
    * [Company Weeklies](en/weekly-syncs/company-weeklies/README.md)
      * [1st September 2021](en/weekly-syncs/company-weeklies/1st-september-2021.md)
* [Meeting Notes](ko/README.md)
  * [Table of contents](ko/SUMMARY.md)
  * [daily-syncs](ko/daily-syncs/README.md)
    * [Design Standups](ko/daily-syncs/design-standups/README.md)
      * [September 2021](ko/daily-syncs/design-standups/september-2021/README.md)
        * [Week 1 (6 - 10 Sept)](ko/daily-syncs/design-standups/september-2021/week-1-6-10-sept.md)
  * [other-regulars](ko/other-regulars/README.md)
    * [Company Weeklies](ko/other-regulars/company-weeklies/README.md)
      * [September 14th 2021](ko/other-regulars/company-weeklies/september-14th-2021.md)
  * [weekly-syncs](ko/weekly-syncs/README.md)
    * [Company Weeklies](ko/weekly-syncs/company-weeklies/README.md)
      * [1st September 2021](ko/weekly-syncs/company-weeklies/1st-september-2021.md)
